name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        run: curl ${{secrets.RENDER_DEPLOY_HOOK}}
  notify_failure:
    needs: [build_and_test]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: success message to discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: "Failure"
  notify_success:
    needs: [deploy]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: failure message to discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: "Success"
          nodetail: true
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
